language: bash
services: docker
branches:
  only:
    - master
env:
  - ARCH=x86_64 RCLONE_ARCH=amd64 RCLONE_VERSION=current
  - ARCH=armhf  RCLONE_ARCH=arm   RCLONE_VERSION=current
before_script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
script:
  - wget --no-check-certificate https://downloads.rclone.org/rclone-${RCLONE_VERSION}-linux-${RCLONE_ARCH}.zip
  - unzip rclone-${RCLONE_VERSION}-linux-${RCLONE_ARCH}.zip
  - mv ./rclone-*-linux-${RCLONE_ARCH}/rclone .
  - docker build -t lafin/rclone:${ARCH} .
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
      if [[ $(docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD") ]]; then
        docker push lafin/rclone;
      fi
    fi
